import localFont from "next/font/local";
import Footer from "./components/(share)/Footer";
import NavbarComponent from "./components/(share)/NavbarComponent";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <nav>
            <NavbarComponent />
          </nav>
<<<<<<< HEAD
          <div className="min-h-screen">{children}</div>
=======
          
          <div className="">{children}</div>
>>>>>>> 92e91cb3ce48e501129f9bec6e6f7d5f1eb7a0ca
         <Footer/>
        </Providers>
      </body>
    </html>
  );
}
